### ISSUE TITLE
ubuntu use rvm install way

### ISSUE THREAD

**Issue by qiaofeng1227** [websoft9dev/role_ruby#1]

**Comment by qiaofeng1227** [comment]
`ruby` command can't running in current Shell, need open new Shell Windows to run this command

**Comment by qiaofeng1227** [comment]
> `by` command can't running in current Shell, need open new Shell Windows to run this command

set softlink for all ruby-cli in current Shell process
```
- name: Get ruby version
  shell: ls /usr/local/rvm/rubies |grep ruby
  register: ruby_dir_name

- name: Get ruby clis
  shell: ls /usr/local/rvm/rubies/{{ruby_dir_name.stdout}}/bin
  register: ruby_clis

- name: Create link
  file:
    src: '/usr/local/rvm/rubies/{{ruby_dir_name.stdout}}/bin/{{item}}'
    dest: '/usr/bin/{{item}}'
    state: link
    force: yes
  with_items: "{{ruby_clis.stdout_lines |list}}"
```
Done
