### ISSUE TITLE
SSL Certificate verify failed

### ISSUE THREAD

**Issue by morning-tan** [websoft9dev/role_ruby#10]
华为云-带T测试 

![image](https://user-images.githubusercontent.com/54173243/153132058-8c28198a-e677-463f-a55d-296bddfebb51.png)

**Comment by qiaofeng1227** [comment]
```
- name: Download RVM installer
  get_url:
    url: "{{ruby_rvm.url}}"
    dest: "{{ruby_rvm.download_path}}"
    validate_certs: no(add)
```
